server:
  port: 8080
  
spring:
  application:
    name: restaurant-booking-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true

dgs:
  graphql:
    schema-locations:
      - "classpath:/schema/*.graphqls"

logging:
  level:
    edu.restaurant: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{correlationId}] - %msg%n"
